apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-sql
data:
  init.sql: |
    create database if not exists mydb;
    use mydb; 
    create table if not exists users(
    id int auto_increment primary key,
    name varchar(255) not null
    );
    insert into users (name) values ('Alice'), ('Bob'), ('Charlie');